<?php

return [
    /*
    |--------------------------------------------------------------------------
    | QBO Menu Configuration
    |--------------------------------------------------------------------------
    |
    | This file contains the default menu items for the QBO-style sidebar.
    | Items can be customized per-user via the database.
    |
    */

    'items' => [
        // Apps (can be pinned)
        [
            'key' => 'accounting',
            'label' => 'Accounting',
            'route' => 'dashboard',
            'icon' => 'ti ti-calculator',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/accounting/1/0/0/accounting.svg',
            'color' => 'linear-gradient(135deg, #1E88E5, #1565C0)',
            'type' => 'menu',
            'position' => 10,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'expenses',
            'label' => 'Expenses & Pay Bills',
            'route' => null,
            'icon' => 'ti ti-receipt-2',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/expenses/1/0/0/expenses.svg',
            'color' => 'linear-gradient(135deg, #43A047, #2E7D32)',
            'type' => 'menu',
            'position' => 11,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'sales',
            'label' => 'Sales & Get Paid',
            'route' => null,
            'icon' => 'ti ti-currency-dollar',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/sales-payments/1/0/0/sales-payments.svg',
            'color' => 'linear-gradient(135deg, #00897B, #00695C)',
            'type' => 'menu',
            'position' => 12,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'customers',
            'label' => 'Customer Hub',
            'route' => 'customer.index',
            'icon' => 'ti ti-users',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/customers/1/0/0/customers.svg',
            'color' => 'linear-gradient(135deg, #00ACC1, #00838F)',
            'type' => 'menu',
            'position' => 13,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'team',
            'label' => 'Team',
            'route' => 'employee.index',
            'icon' => 'ti ti-briefcase',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/team/1/0/0/team.svg',
            'color' => 'linear-gradient(135deg, #5E35B1, #4527A0)',
            'type' => 'menu',
            'position' => 14,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'time',
            'label' => 'Time',
            'route' => null,
            'icon' => 'ti ti-clock',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/time/1/0/0/time.svg',
            'color' => 'linear-gradient(135deg, #3949AB, #283593)',
            'type' => 'menu',
            'position' => 15,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'inventory',
            'label' => 'Inventory',
            'route' => 'productservice.index',
            'icon' => 'ti ti-archive',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/inventory/1/0/0/inventory.svg',
            'color' => 'linear-gradient(135deg, #039BE5, #0277BD)',
            'type' => 'menu',
            'position' => 16,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'sales_tax',
            'label' => 'Sales Tax',
            'route' => 'taxes.index',
            'icon' => 'ti ti-receipt-tax',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/sales-tax/1/0/0/sales-tax.svg',
            'color' => 'linear-gradient(135deg, #E53935, #C62828)',
            'type' => 'menu',
            'position' => 17,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'business_tax',
            'label' => 'Business Tax',
            'route' => null,
            'icon' => 'ti ti-building',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/business-tax/1/0/0/business-tax.svg',
            'color' => 'linear-gradient(135deg, #8E24AA, #6A1B9A)',
            'type' => 'menu',
            'position' => 18,
            'is_visible' => true,
            'pinnable' => true,
        ],
        [
            'key' => 'lending',
            'label' => 'Lending',
            'route' => null,
            'icon' => 'ti ti-coin',
            'icon_url' => 'https://asset-service-cdn-prdasset-prd.a.intuit.com/navigationfusionga/lending/1/0/0/lending.svg',
            'color' => 'linear-gradient(135deg, #7CB342, #558B2F)',
            'type' => 'menu',
            'position' => 19,
            'is_visible' => true,
            'pinnable' => true,
        ],
    ],

    // Create menu items
    'create_items' => [
        [
            'key' => 'create_invoice',
            'label' => 'Invoice',
            'route' => 'invoice.create',
            'icon' => 'ti ti-file-invoice',
        ],
        [
            'key' => 'create_expense',
            'label' => 'Expense',
            'route' => 'expense.create',
            'icon' => 'ti ti-receipt',
        ],
        [
            'key' => 'create_bill',
            'label' => 'Bill',
            'route' => 'bill.create',
            'icon' => 'ti ti-file-text',
        ],
        [
            'key' => 'create_customer',
            'label' => 'Customer',
            'route' => 'customer.create',
            'icon' => 'ti ti-user-plus',
        ],
        [
            'key' => 'create_vendor',
            'label' => 'Vendor',
            'route' => 'vender.create',
            'icon' => 'ti ti-building',
        ],
        [
            'key' => 'create_product',
            'label' => 'Product/Service',
            'route' => 'productservice.create',
            'icon' => 'ti ti-package',
        ],
    ],

    // Bookmarkable pages (for customize bookmarks modal)
    'bookmarkable_pages' => [
        ['key' => 'home', 'label' => 'Home', 'route' => 'dashboard'],
        ['key' => 'feed', 'label' => 'Feed', 'route' => null],
        ['key' => 'standard_reports', 'label' => 'Standard reports', 'route' => 'reports'],
        ['key' => 'custom_reports', 'label' => 'Custom reports', 'route' => null],
        ['key' => 'management_reports', 'label' => 'Management reports', 'route' => null],
        ['key' => 'cash_flow_planner', 'label' => 'Cash flow planner', 'route' => null],
        ['key' => 'budgets', 'label' => 'Budgets', 'route' => null],
        ['key' => 'bank_transactions', 'label' => 'Bank transactions', 'route' => null],
        ['key' => 'integration_transactions', 'label' => 'Integration transactions', 'route' => null],
        ['key' => 'receipts', 'label' => 'Receipts', 'route' => null],
        ['key' => 'reconcile', 'label' => 'Reconcile', 'route' => null],
        ['key' => 'rules', 'label' => 'Rules', 'route' => null],
        ['key' => 'chart_of_accounts', 'label' => 'Chart of accounts', 'route' => 'chartofaccount.index'],
        ['key' => 'recurring_transactions', 'label' => 'Recurring transactions', 'route' => null],
        ['key' => 'my_accountant', 'label' => 'My accountant', 'route' => null],
        ['key' => 'expense_transactions', 'label' => 'Expense transactions', 'route' => 'expense.index'],
        ['key' => 'vendors', 'label' => 'Vendors', 'route' => 'vender.index'],
        ['key' => 'bills', 'label' => 'Bills', 'route' => 'bill.index'],
        ['key' => 'bill_payments', 'label' => 'Bill payments', 'route' => null],
        ['key' => 'mileage', 'label' => 'Mileage', 'route' => null],
        ['key' => 'contractors', 'label' => 'Contractors', 'route' => null],
        ['key' => '1099s', 'label' => '1099s', 'route' => null],
        ['key' => 'sales_overview', 'label' => 'Sales overview', 'route' => null],
        ['key' => 'sales_transactions', 'label' => 'Sales transactions', 'route' => null],
        ['key' => 'invoices', 'label' => 'Invoices', 'route' => 'invoice.index'],
        ['key' => 'recurring_payments', 'label' => 'Recurring payments', 'route' => null],
        ['key' => 'sales_orders', 'label' => 'Sales orders', 'route' => null],
        ['key' => 'sales_channels', 'label' => 'Sales channels', 'route' => null],
        ['key' => 'quickbooks_payouts', 'label' => 'QuickBooks payouts', 'route' => null],
        ['key' => 'channel_payouts', 'label' => 'Channel payouts', 'route' => null],
        ['key' => 'products_services', 'label' => 'Products & services', 'route' => 'productservice.index'],
        ['key' => 'customers_overview', 'label' => 'Customers overview', 'route' => null],
        ['key' => 'customers', 'label' => 'Customers', 'route' => 'customer.index'],
        ['key' => 'estimates', 'label' => 'Estimates', 'route' => 'proposal.index'],
        ['key' => 'reviews', 'label' => 'Reviews', 'route' => null],
        ['key' => 'marketing', 'label' => 'Marketing', 'route' => null],
        ['key' => 'payroll_overview', 'label' => 'Payroll overview', 'route' => null],
        ['key' => 'benefits', 'label' => 'Benefits', 'route' => null],
        ['key' => 'hr_advisor', 'label' => 'HR advisor', 'route' => null],
        ['key' => 'compliance', 'label' => 'Compliance', 'route' => null],
        ['key' => 'employees', 'label' => 'Employees', 'route' => 'employee.index'],
        ['key' => 'workers_comp', 'label' => 'Workers\' comp', 'route' => null],
        ['key' => 'time_entries', 'label' => 'Time entries', 'route' => null],
        ['key' => 'schedule', 'label' => 'Schedule', 'route' => null],
        ['key' => 'inventory_overview', 'label' => 'Inventory overview', 'route' => null],
        ['key' => 'inventory', 'label' => 'Inventory', 'route' => 'productservice.index'],
        ['key' => 'purchase_orders', 'label' => 'Purchase orders', 'route' => 'purchase.index'],
        ['key' => 'shipping_labels', 'label' => 'Shipping labels', 'route' => null],
        ['key' => 'sales_tax_overview', 'label' => 'Sales Tax overview', 'route' => 'taxes.index'],
        ['key' => 'business_tax_overview', 'label' => 'Business Tax overview', 'route' => null],
        ['key' => 'tax_summary', 'label' => 'Tax summary', 'route' => null],
        ['key' => 'lending_overview', 'label' => 'Lending overview', 'route' => null],
        ['key' => 'term_loan', 'label' => 'Term loan', 'route' => null],
        ['key' => 'ppp_center', 'label' => 'PPP Center', 'route' => null],
    ],
];
